import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { getProgressStats } from '../services/progressService';
import {
  BookOpen,
  FileText,
  Brain,
  BarChart2,
  FolderOpen,
  HelpCircle,
  ArrowRight,
  Sparkles,
  TrendingUp,
} from 'lucide-react';

const StatCard = ({ icon: Icon, label, value, sub, color }) => (
  <div className="glass-panel rounded-2xl p-5 flex items-center gap-4 relative overflow-hidden group hover:border-white/20 transition">
    <div className={`p-3 rounded-xl ${color} shadow-lg shadow-black/20 flex-shrink-0`}>
      <Icon className="w-6 h-6 text-white" />
    </div>
    <div className="min-w-0">
      <p className="text-2xl lg:text-3xl font-bold text-white">{value ?? '—'}</p>
      <p className="text-xs text-gray-400 font-medium truncate">{label}</p>
      {sub && <p className="text-[11px] text-gray-500 mt-0.5">{sub}</p>}
    </div>
  </div>
);

const QuickLink = ({ to, icon: Icon, label, description, color }) => (
  <Link
    to={to}
    className="glass-panel rounded-2xl p-5 hover:bg-white/10 hover:border-white/20 transition-all duration-200 group flex flex-col justify-between"
  >
    <div>
      <div className={`p-2.5 rounded-xl w-fit ${color} mb-3 shadow-md`}>
        <Icon className="w-5 h-5 text-white" />
      </div>
      <h3 className="font-semibold text-white group-hover:text-blue-300 transition text-sm">
        {label}
      </h3>
      <p className="text-xs text-gray-400 mt-1 line-clamp-2 leading-relaxed">{description}</p>
    </div>
    <div className="flex items-center gap-1 text-xs text-blue-400 font-medium mt-4 group-hover:translate-x-1 transition duration-200">
      Open <ArrowRight className="w-3.5 h-3.5" />
    </div>
  </Link>
);

export default function Dashboard() {
  const { user } = useAuth();
  const [stats, setStats] = useState(null);

  useEffect(() => {
    getProgressStats()
      .then((res) => setStats(res.data.stats))
      .catch(() => {});
  }, []);

  const totalNotes = stats?.totalNotes ?? 0;
  const totalQuizzes = stats?.totalQuizzesTaken ?? 0;
  const avgScore = stats ? `${stats.avgPercentage}%` : '0%';

  return (
    <div className="space-y-8">
      {/* Welcome Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl lg:text-3xl font-bold text-white">
            Welcome back, <span className="gradient-text">{user?.name?.split(' ')[0]}</span> 👋
          </h1>
          <p className="text-gray-400 text-sm mt-1">
            Role: <span className="text-blue-400 font-medium">{user?.role}</span> • Ready to learn and test your recall today?
          </p>
        </div>

        <Link
          to="/notes"
          className="flex items-center gap-2 px-4 py-2 rounded-xl gradient-btn text-white text-sm font-semibold shadow-md shadow-blue-500/20"
        >
          <Sparkles className="w-4 h-4" /> Go to Workspace
        </Link>
      </div>

      {/* Hero Learning Recommendation Banner */}
      <div className="glass-panel rounded-2xl p-6 border border-white/10 bg-gradient-to-r from-blue-950/40 via-purple-950/30 to-indigo-950/40 flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-purple-500/20 text-purple-300 border border-purple-500/30">
            <Sparkles className="w-3.5 h-3.5" /> Week 4 Feature Active
          </div>
          <h2 className="text-xl font-bold text-white">
            Interactive Flashcards & AI Quiz Stepper
          </h2>
          <p className="text-xs text-gray-300 max-w-xl leading-relaxed">
            Boost memory retention with 3D flip card active recall and test your comprehension with real-time graded quizzes generated by Google Gemini.
          </p>
        </div>

        <div className="flex items-center gap-3 flex-shrink-0">
          <Link
            to="/flashcards"
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white text-xs font-semibold transition shadow-md shadow-violet-600/20"
          >
            <BookOpen className="w-4 h-4" /> Flashcards
          </Link>
          <Link
            to="/quiz"
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold transition shadow-md shadow-purple-600/20"
          >
            <HelpCircle className="w-4 h-4" /> Start Quiz
          </Link>
        </div>
      </div>

      {/* KPI Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          icon={FileText}
          label="Total Notes"
          value={stats?.totalNotes}
          sub="Written notes"
          color="bg-blue-600"
        />
        <StatCard
          icon={FolderOpen}
          label="Subjects Studied"
          value={stats?.subjectsStudied}
          sub="Organized subjects"
          color="bg-indigo-600"
        />
        <StatCard
          icon={HelpCircle}
          label="Quizzes Taken"
          value={totalQuizzes}
          sub="Assessments completed"
          color="bg-violet-600"
        />
        <StatCard
          icon={TrendingUp}
          label="Avg. Score"
          value={stats ? avgScore : null}
          sub="Overall test accuracy"
          color="bg-purple-600"
        />
      </div>

      {/* Quick Links */}
      <div>
        <h2 className="text-lg font-semibold text-gray-200 mb-4">Study Workspace Shortcuts</h2>
        <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
          <QuickLink
            to="/subjects"
            icon={FolderOpen}
            label="Subjects Catalog"
            description="Manage or browse your academic subjects"
            color="bg-blue-600"
          />
          <QuickLink
            to="/notes"
            icon={FileText}
            label="Study Notes Editor"
            description="Create rich markdown notes with tag indexing"
            color="bg-indigo-600"
          />
          <QuickLink
            to="/flashcards"
            icon={BookOpen}
            label="3D Flashcard Decks"
            description="Practice active recall with interactive 3D cards"
            color="bg-violet-600"
          />
          <QuickLink
            to="/quiz"
            icon={HelpCircle}
            label="Interactive Quizzes"
            description="Take multiple-choice tests with instant grading"
            color="bg-purple-600"
          />
          <QuickLink
            to="/progress"
            icon={BarChart2}
            label="Learning Progress"
            description="Detailed scores, attempt history, and analytics"
            color="bg-fuchsia-600"
          />
          <QuickLink
            to="/notes"
            icon={Brain}
            label="AI Study Tools"
            description="Generate summaries, flashcards, and quizzes in 1-click"
            color="bg-pink-600"
          />
        </div>
      </div>
    </div>
  );
}
